# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='prof_image',
            field=models.ImageField(blank=True, default='media/profile_images/default.png', null=True, upload_to='profile_images'),
        ),
    ]
