# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_prof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='prof_image',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images'),
        ),
    ]
